backend:
  name: git-gateway
  branch: master-source # Branch to update (optional; defaults to master)

media_folder: "static/img/uploads"
public_folder: "img/uploads"

collections:
  - name: posts
    preview_path: blog/{{year}}/{{month}}/{{title}}
    preview_path_date_field: published_at
    fields:
      - {name: title, label: Title }
        {name: published_at, label: Published At, widget: date }
        {name: body, label: Body, widget: markdown }

publish_mode: editorial_workflow
